name: 🐞 Found a Bug?
description: Spotted something off? Let us know.
title: '[Bug]: '
assignees:
  - avalynndev
body:
  - type: input
    id: bug-description
    attributes:
      label: What went wrong?
      description: Tell us about the bug like you're telling a friend. Keep it simple and clear.
      placeholder: 'Like, when I try to play a video, it just won’t start...'
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How'd you stumble upon it?
      description: Walk us through how you found this bug, step by step.
      placeholder: "1. I was on the homepage\n2. Clicked on the play button\n3. And boom, nothing happened"
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: What you hoped for vs. What actually happened
      description: Share what you were expecting and then what really went down.
      placeholder: "Hoped for: A cool video starts playing.\nBut actually: Got a whole lot of nothing."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Anything else we should know?
      description: Got more details or a screenshot? Throw them in here.
      placeholder: 'FYI: This only happens in Chrome for me...'
    validations:
      required: false

  - type: dropdown
    id: browsers-affected
    attributes:
      label: Which browsers were a bummer?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Got logs?
      description: If you've got some techy details or logs, we'd love to see them.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct Agreement
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
